config/routes.rb
Rails.application.routes.draw do
  resources :campaigns
  resources :users, only: [:new, :create, :edit, :update, :show]

  root 'campaigns#index'

  get 'signup' => 'users#new'
  post 'signup' => 'users#create'
  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'

end

app/models/campaign.rb
# == Schema Information
#
# Table name: campaigns
#
#  id          :integer          not null, primary key
#  user_id     :integer
#  title       :string
#  description :text
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

class Campaign < ActiveRecord::Base
  belongs_to :user
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :integer          not null, primary key
#  email           :string
#  password_digest :string
#  display_name    :string
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#

class User < ActiveRecord::Base
  has_secure_password

  has_many :campaigns

  validates :email, presence: true, uniqueness: true
  validates :password, presence: true, length: { minimum: 4 }, on: :create


  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST : BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/campaigns_controller.rb
class CampaignsController < ApplicationController
  before_action :logged_in_user, only: [:new, :create, :edit, :update, :destroy]
  before_action :correct_user, only: [:edit, :update, :destroy]

  def new
    @campaign = Campaign.new
  end

  def create
    @campaign = current_user.campaigns.build(campaign_params)

    if @campaign.save
      flash[:notice] = "Your campaign was created successfully!"
      redirect_to campaign_path(@campaign)
    else
      flash.now[:alert] = "Something went wrong!"
      render 'new'
    end
  end

  def index
    @campaigns = Campaign.all
  end

  def show
    @campaign = Campaign.find(params[:id])
  end

  def edit
    @campaign = Campaign.find(params[:id])
  end

  def update
    @campaign = Campaign.find(params[:id])
    if @campaign.update campaign_params
      flash[:notice] = "Your campaign was created successfully!"
      redirect_to campaign_path(@campaign)
    else
      flash.now[:alert] = "Something went wrong!"
      render 'new'
    end
  end

  def destroy
  end

  private
    def campaign_params
      params.require(:campaign).permit(:title, :description)
    end

    def correct_user
      campaign = Campaign.find(params[:id])
      raise ActionController::RoutingError.new('Not Found') unless current_user.id == campaign.user_id
    end
    
    def logged_in_user
      unless logged_in?
        flash[:alert] = "You need to log in first"
        redirect_to login_url
      end
    end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    user = User.find_by(email: params[:session][:email])
    if user && user.authenticate(params[:session][:password])
      log_in user
      flash[:notice] = 'Welcome back!'
      redirect_to root_url
    else 
      flash.now[:alert] = 'Invalid email address or password.'
      render 'new'
    end
  end

  def destroy
    log_out
    redirect_to root_url
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in_user, only: [:edit, :update]
  before_action :correct_user, only: [:edit, :update]

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      flash[:notice] = "Signed up successfully. Welcome to the party!"
      log_in @user
      redirect_to root_path
    else
      flash[:alert] = @user.errors.full_messages.join(", ")
      render 'new'
    end
  end

  def show
    @user = User.find(params[:id])
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update user_params
      flash[:notice] = "Account updated successfully."
      redirect_to edit_user_path @user
    else
      flash[:alert] = @user.errors.full_messages.join(", ")
      redirect_to edit_user_path @user
    end
  end

  private
    def user_params
      params.require(:user).permit(:email, :password, :password_confirmation)
    end

    def logged_in_user
      unless logged_in?
        flash[:alert] = "Please log in first"
        redirect_to login_url
      end
    end

    def correct_user
      @user = User.find(params[:id])
      raise ActionController::RoutingError.new('Not Found') unless current_user == @user
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/campaigns_helper.rb
module CampaignsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def log_in(user) 
    session[:user_id] = user.id
  end

  def logged_in?
    !current_user.nil?
  end

  def log_out
    session.delete(:user_id)
    @current_user = nil
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/campaigns/edit.html.erb
<div class="content">
  <div class="row">
    <div class="col-md-6 col-md-offset-3">
      <h1>edit campaign</h1>


      <%= form_for @campaign do |f| %>
        <%= f.label :title %>
        <%= f.text_field :title, class: 'form-control'  %>

        <%= f.label :description %>
        <%= f.text_field :description, class: 'form-control'  %>

        <br />

        <%= f.submit "Update", class: "btn btn-lg btn-primary" %>

      <% end %>

    </div> 
  </div>
</div>

app/views/campaigns/index.html.erb
<div class="content">
  <div class="row">
    <div class="col-md-6 col-md-offset-3">
      <h1>campaigns</h1>

      <ul>
        <% @campaigns.each do |campaign| %>
          <li><%= link_to campaign.title, campaign %></li>
        <% end %>
      </ul>

    </div> 
  </div>
</div>

app/views/campaigns/new.html.erb
<div class="content">
  <div class="row">
    <div class="col-md-6 col-md-offset-3">
      <h1>new campaign</h1>

      <%= form_for @campaign do |f| %>
        <%= f.label :title %>
        <%= f.text_field :title, class: 'form-control'  %>

        <%= f.label :description %>
        <%= f.text_field :description, class: 'form-control'  %>

        <br />

        <%= f.submit "Create", class: "btn btn-lg btn-primary" %>

      <% end %>
    </div> 
  </div>
</div>

app/views/campaigns/show.html.erb
<div class="content">
  <div class="row">
    <div class="col-md-6 col-md-offset-3">
      <h1><%= @campaign.title %></h1>

      <div><%= @campaign.description %></div>

    </div> 
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>App</title>
  <link href='http://fonts.googleapis.com/css?family=Open+Sans' rel='stylesheet' type='text/css'>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div id="body-wrapper">
    <div id="content-wrapper">
    
      <%= render 'shared/navbar' %>
      <%= render 'shared/alerts' %>

      <%= yield %>

    </div>

    <%#= debug(params) if Rails.env.development? %>

    <%= render 'shared/footer' %>
  </div>

</body>
</html>

app/views/shared/_alerts.html.erb
<div class="content">
  <div class="row">
    <div class="col-md-6 col-md-offset-3">
      <% if notice %>
        <div class="alert alert-success alert-dismissible" role="alert">
          <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
          <%= notice %>
        </div>
      <% end %>
      <% if alert %>
        <div class="alert alert-danger alert-dismissible" role="alert">
          <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
            <%= alert %>
        </div>
      <% end %>       
    </div> 
  </div>
</div>

app/views/shared/_footer.html.erb
<div id="footer">
  <div class="container">
    <div class="row">
      <div class="col-md-12">
        <div class="text-center">           
          <small class="text-muted">© 2066 Global Solutions, Inc.</small>
          <br />
          <small class="text-muted">"We Own the Future"</small>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/shared/_navbar.html.erb
<nav id="navbar" class="navbar gradient" role="navigation">

  <div class="container">

    <a class="navbar-brand" href="/">Brand Logo</a>

    <div class="nav pull-right">

      <ul class="nav navbar-nav">
        <%= render 'shared/session_control' %>
      </ul>
    </div>

  </div>
</nav>

app/views/shared/_session_control.html.erb
<% if logged_in? %>
  <li>
    <%= link_to("New Campaign", new_campaign_path, html_options = {class: "btn btn-lg btn-primary"}) %>
  </li> 
  <li class="dropdown">
  <a class="dropdown-toggle" id="session-menu" data-toggle="dropdown" href="javascript:;">

    <div class="hidden-xs">
      Welcome, <%= current_user.email %>
      <span class="caret"></span>
    </div>
    <div class="visible-xs">
      <i class="fa fa-user"></i>
    </div>

  </a>
  <ul class="dropdown-menu" role="menu" aria-labelledby="session-menu">
    <li role="presentation"><%= link_to 'Edit Profile', edit_user_path(current_user), :class => 'navbar-link' %></li>
    <li role="presentation"><%= link_to "Logout", logout_path, method: :delete, :class => 'navbar-link' %></li>
  </ul>
</li>

<% else %>
  <li><%= link_to "Sign up", signup_path, :class => 'navbar-link'  %></li>
  <li><%= link_to "Login", login_path, :class => 'navbar-link'  %></li>
<% end %>

app/views/users/edit.html.erb
<div class="content">
  <div class="row">
    <div class="col-md-6 col-md-offset-3">
      <h1>edit user</h1>

      <%= form_for @user do |f| %>
        <%= f.label :email %>
        <%= f.text_field :email, class: 'form-control'  %>

        <%#= f.label :password %>
        <%#= f.password_field :password, class: 'form-control'  %>

        <%#= f.label :password_confirmation %>
        <%#= f.password_field :password_confirmation, class: 'form-control'  %>

        <br />

        <%= f.submit "Update", class: "btn btn-lg btn-primary" %>

      <% end %>
    </div> 
  </div>
</div>

app/views/users/new.html.erb
<div class="content">
  <div class="row">
    <div class="col-md-4 col-md-offset-4">
      <h1>sign up</h1>

      <%= form_for @user do |f| %>
        <%= f.label :email %>
        <%= f.text_field :email, class: 'form-control'  %>

        <%= f.label :password %>
        <%= f.password_field :password, class: 'form-control'  %>

        <%= f.label :password_confirmation %>
        <%= f.password_field :password_confirmation, class: 'form-control'  %>

        <br />

        <%= f.submit "Sign up", class: "btn btn-lg btn-primary" %>

      <% end %>

    </div> 
  </div>
</div>

app/views/users/show.html.erb
<div class="content">
  <div class="row">
    <div class="col-md-6 col-md-offset-3">
      <h1>show user</h1>

    </div> 
  </div>
</div>